Cypress.Commands.add('fillMandatoryFieldsAndSubmit', function () {
    const textLong = 'Salve o tricolor paulista, amado clube brasileiro. Tu és forte tú és grande, dentre os grande és o primeiro'
    cy.get('#firstName')
        .should('be.visible')
        .type('Bruno')
    cy.get('#lastName')
        .should('be.visible')
        .type('Garcia')
    cy.get('#email')
        .should('be.visible')
        .type('bruno@teste.com.br')
    cy.get('#open-text-area')
        .should('be.visible')
        .type(textLong, { delay: 0 })
    cy.contains('button','Enviar').click()
})

Cypress.Commands.add('fillEmailFieldWithInvalidValue', function() {
cy.get('#firstName')
    .should('be.visible')
    .type('Bruno')
cy.get('#lastName')
    .should('be.visible')
    .type('Garcia')
cy.get('#email')
    .should('be.visible')
    .type('brunoteste.com')
cy.get('#open-text-area')
    .should('be.visible')
    .type('Teste')
cy.contains('button','Enviar').click()
})

Cypress.Commands.add('notFillPhoneWhenItIsMandatory', function() {
    cy.get('#firstName')
      .should('be.visible')
      .type('Bruno')
    cy.get('#lastName')
      .should('be.visible')
      .type('Garcia')
    cy.get('#email')
      .should('be.visible')
      .type('bruno@teste.com.br')
    cy.get('#open-text-area')
      .should('be.visible')
      .type('Teste')
    cy.get('#phone-checkbox').check()
    cy.contains('button','Enviar').click()
})

Cypress.Commands.add('cleanFieldsValues', function() {
    const firstName = 'Bruno'
    const lastName = 'Garcia'
    const email = 'bruno@teste.com.br'
    const telefone = '11940702423'
    cy.get('#firstName')
      .type(firstName)
      .should('have.value', firstName)
      .clear()
      .should('have.value', '')
    cy.get('#lastName')
      .type(lastName)
      .should('have.value', lastName)
      .clear()
      .should('have.value', '')
    cy.get('#email')
      .type(email)
      .should('have.value', email)
      .clear()
      .should('have.value', '')
    cy.get('#phone-checkbox')
      .click()
    cy.get('#phone')
      .type(telefone)
      .should('have.value', telefone)
      .clear()
      .should('have.value', '')
})
